# fly.toml app configuration file generated for barbershop-backend on 2024-05-31T16:59:13-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'barbershop-backend'
primary_region = 'phx'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false  # Deshabilitado para mantener el servidor siempre encendido
  auto_start_machines = true
  min_machines_running = 1  # Asegura que al menos una máquina esté siempre encendida
  processes = ['app']

[[vm]]
  memory = '512mb'  # Cambiado de '1gb' a '512mb' para reducir costos
  cpu_kind = 'shared'
  cpus = 1
